### ISSUE TITLE
Add diff-so-fancy

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#114]
https://github.com/so-fancy/diff-so-fancy

**Comment by gabebw** [comment]
I'll jump on with you and @adarsh: I personally use `diff-highlight` instead of the full `diff-so-fancy`: https://github.com/gabebw/dotfiles/commit/21c34ef8fd2a360b52b4c94c3d22a3d192806a52

diff-so-fancy does a lot, but `diff-highlight` just makes diffs look like they do on github (word-based, green/red background). I'm a big fan. 

Since `diff-highlight` isn't in diff-so-fancy's bin directory, it does require a little bit of messing about...or you can just copy these three lines: https://github.com/gabebw/dotfiles/blob/220de8248e678f4590ae93d0d3f668a997833b3b/tag-git/zsh/git.zsh#L49-L51

**Comment by christoomey** [comment]
I've been using diff-so-fancy for a bit, and very much enjoying it. Do recommend!
