### ISSUE TITLE
git-opr

### ISSUE THREAD

**Issue by jaredgalanis** [christoomey/dotfiles#125]
Hey Chris, I'm just about finished with your awesome Mastering Git series on Upcase. I've learned a lot so far and definitely will come back to watch it all a second time.

I noticed that the version of the git-opr file you reference in the Upcase notes for [the remotes video](https://thoughtbot.com/upcase/videos/git-github-and-remotes) has a reference to an older version of this file.

I found the most recent version and I tried using it for one of my company's projects, but I am getting a "Not found" error when curl'ing the github api. I'm assuming this has something to do with my level of ssh access to the git repo's at my org.  

That being the case I opted for using your `open_pull_request_for_repo_branch(repo, branch)` method, but I think the repo/remote_url variable already includes `//github.com` and so the url that it attempts to open is broken. Just removing that gets it opening properly for me:

```
def open_pull_request_for_repo_branch(repo, branch)
  system("open https:#{repo}/pull/#{branch}")
end
```

Many thanks again for all of your hard work on the Upcase product and sharing this info as well!

**Comment by christoomey** [comment]
Hi @jaredgalanis thanks for the kind words! I'm really glad you found the videos valuable.

I've actually updated the script a bit more (I just pushed up those changes) and it no longer uses the offending method, so I think that's why I wasn't seeing this issue. You can check that out here: https://github.com/christoomey/dotfiles/blob/master/bin/git-opr.

I'm going to close this now as things are working fine for me, and hopefully you'll find the update to work for you (note it requires `chrome-cli`).
